import { describe, expect, it } from "vitest";
import { CANONICAL, ReferralRailClient, ValidationError, findCreatedOpportunity, fundingFor, getAvailableActions, redactError, sameCreatedOpportunity } from "../src/index.js";
import { externalAllocations, feeMethod, settlementRecipients } from "../src/fees.js";
import type { Address } from "viem";
import type { CreateOpportunityInput, Opportunity } from "../src/types.js";

const addr = (hex: string) => hex as Address;
const employer = addr("0x0000000000000000000000000000000000000001");
const candidate = addr("0x0000000000000000000000000000000000000002");
const referrer = addr("0x0000000000000000000000000000000000000003");
const input: CreateOpportunityInput = { title: "Build integration", brief: "Implement this integration with tests and documentation.", acceptanceCriteria: "The merged pull request must include substantive code and tests.", repoOwner: "example", repoName: "repo", candidateAddress: candidate, candidatePayment: 2n, referralReward: 1n, referralWindowSeconds: 120, completionWindowSeconds: 300 };
function fixture(overrides: Partial<Opportunity> = {}): Opportunity { return { id: 1, employer, candidate, title: input.title, brief: input.brief, acceptance_criteria: input.acceptanceCriteria, repo_owner: input.repoOwner, repo_name: input.repoName, candidate_payment: 2n, referral_reward: 1n, funded_amount: 3n, created_at: 10, referral_deadline: 100, completion_deadline: 300, state: "OPEN", state_code: 1, referrer, candidate_github: "", referred_at: 0, accepted_at: 0, active_attempt: 0, attempt_count: 0, active_pr_number: 0, evidence_submitted_at: 0, judgment_timeout_at: 0, retry_deadline: 0, last_outcome: "NONE", last_outcome_code: 0, last_evidence_digest: "", last_reason: "", last_audit: "", closed_at: 0, settlement_released: false, ...overrides }; }
const action = (o: Opportunity, name: string, context: Address | undefined, now: number) => getAvailableActions(o, { address: context, now }).find(item => item.action === name)!;

describe("ReferralRail SDK", () => {
  it("pins the canonical deployment and rejects wrong chain or RPC", () => { expect(CANONICAL).toMatchObject({ chainId: 61997, referralRail: "0x1BB0B68da8cD29C77aa2B5F4C312E806BfCDCEA5", outcomeJudge: "0xd0C840fdD6654f501060b048F163BAD526A80724" }); expect(() => new ReferralRailClient({ chainId: 61999 })).toThrow(/locked/); expect(() => new ReferralRailClient({ rpcUrl: "https://example.invalid" })).toThrow(/locked/); });
  it("requires a signer for writes while reads need no signer", async () => { const readOnly = new ReferralRailClient(); expect(readOnly.account).toBeUndefined(); await expect(readOnly.submitWork(1, 1)).rejects.toThrow(/signing account/); });
  it("checks exact positive funding", () => { expect(fundingFor(2n, 1n)).toBe(3n); expect(() => fundingFor(0n, 1n)).toThrow(ValidationError); expect(() => fundingFor(2n, 0n)).toThrow(ValidationError); });
  it("decodes role and OPEN referral eligibility", () => { expect(action(fixture(), "create_referral", referrer, 50).allowed).toBe(true); expect(action(fixture(), "create_referral", employer, 50).allowed).toBe(false); expect(action(fixture(), "create_referral", candidate, 50).allowed).toBe(false); expect(action(fixture(), "create_referral", undefined, 50).allowed).toBe(false); });
  it("uses strict deadline boundaries", () => { expect(action(fixture(), "create_referral", referrer, 100).allowed).toBe(true); expect(action(fixture(), "create_referral", referrer, 101).allowed).toBe(false); expect(action(fixture({ state: "ACCEPTED", state_code: 3 }), "submit_work", candidate, 300).allowed).toBe(true); expect(action(fixture({ state: "ACCEPTED", state_code: 3 }), "submit_work", candidate, 301).allowed).toBe(false); expect(action(fixture({ state: "OPEN", state_code: 1 }), "expire", undefined, 100).allowed).toBe(false); expect(action(fixture({ state: "OPEN", state_code: 1 }), "expire", undefined, 101).allowed).toBe(true); });
  it("handles acceptance and retry authorization", () => { expect(action(fixture({ state: "REFERRED", state_code: 2 }), "accept_referral", candidate, 50).allowed).toBe(true); expect(action(fixture({ state: "REFERRED", state_code: 2 }), "accept_referral", referrer, 50).allowed).toBe(false); const inconclusive = fixture({ state: "INCONCLUSIVE", state_code: 5, attempt_count: 1, retry_deadline: 200 }); expect(action(inconclusive, "retry_inconclusive", candidate, 200).allowed).toBe(true); expect(action(inconclusive, "retry_inconclusive", candidate, 201).allowed).toBe(false); expect(action(fixture({ state: "INCONCLUSIVE", state_code: 5, attempt_count: 2, retry_deadline: 999 }), "retry_inconclusive", candidate, 50).allowed).toBe(false); });
  it("advertises recovery only after the contract's conditions", () => { const judging = fixture({ state: "JUDGING", state_code: 4, judgment_timeout_at: 200 }); expect(action(judging, "recover", undefined, 200).allowed).toBe(false); expect(action(judging, "recover", undefined, 201).allowed).toBe(true); const cure = fixture({ state: "INCONCLUSIVE", state_code: 5, attempt_count: 1, retry_deadline: 200 }); expect(action(cure, "recover", undefined, 200).allowed).toBe(false); expect(action(cure, "recover", undefined, 201).allowed).toBe(true); });
  it("distinguishes unreleased PAID and REFUNDED settlement", () => { expect(action(fixture({ state: "PAID", state_code: 6 }), "settle_opportunity", undefined, 1).allowed).toBe(true); expect(action(fixture({ state: "REFUNDED", state_code: 7 }), "settle_opportunity", undefined, 1).allowed).toBe(true); expect(action(fixture({ state: "PAID", state_code: 6, settlement_released: true }), "settle_opportunity", undefined, 1).allowed).toBe(false); expect(settlementRecipients(fixture({ state: "PAID", state_code: 6 }))).toEqual([candidate, referrer]); expect(settlementRecipients(fixture({ state: "REFUNDED", state_code: 7 }))).toEqual([employer]); expect(() => settlementRecipients(fixture({ state: "PAID", state_code: 6, settlement_released: true }))).toThrow(/already/); });
  it("selects method-specific fee paths", () => { expect(feeMethod("submit_work")).toBe("message"); expect(feeMethod("resolve_judgment")).toBe("ordinary"); expect(feeMethod("settle_opportunity")).toBe("external"); expect(externalAllocations([candidate, referrer])).toHaveLength(2); expect(externalAllocations([employer])).toHaveLength(1); });
  it("identifies a created opportunity from the full before/after set", () => { const before = Array.from({ length: 80 }, (_, index) => fixture({ id: index + 1 })); const created = fixture({ id: 81, employer }); const found = findCreatedOpportunity(before, [...before, created], input, employer); expect(found.id).toBe(81); expect(sameCreatedOpportunity(created, input, employer)).toBe(true); expect(() => findCreatedOpportunity(before, before, input, employer)).toThrow(/could not identify/); expect(() => findCreatedOpportunity(before, [...before, created, fixture({ id: 82 })], input, employer)).toThrow(/ambiguous/); });
  it("redacts secrets and does not expose private material in errors", () => { expect(redactError(new Error("private_key=0x" + "a".repeat(64)))).toContain("<redacted>"); });
});
