import { createAccount, createClient, isSuccessful } from "genlayer-js";
import { TransactionHashVariant } from "genlayer-js/types";
import type { Account, Address } from "viem";
import { quoteFees } from "./fees.js";
import { ConfigurationError, TransactionError, ValidationError, redactError } from "./errors.js";
import { V2_CANONICAL, NETWORK, explorerTx } from "./constants.js";
import type { Campaign, CampaignAccounting, CreateCampaignInput, Position, ReferralRailV2Config, V2Action, WriteResult } from "./types.js";

const normalize = (raw: unknown): any => raw instanceof Map ? Object.fromEntries([...raw.entries()].map(([k, v]) => [String(k), normalize(v)])) : Array.isArray(raw) ? raw.map(normalize) : raw && typeof raw === "object" ? Object.fromEntries(Object.entries(raw).map(([k, v]) => [k, normalize(v)])) : raw;
const number = (v: unknown) => Number(v ?? 0);
const bigint = (v: unknown) => BigInt(v as string | number | bigint);
function campaign(raw: unknown): Campaign { const c = normalize(raw); return { ...c, id: number(c.id), max_positions: number(c.max_positions), successful: number(c.successful), pending_successes: number(c.pending_successes), occupied: number(c.occupied), open_positions: number(c.open_positions), reusable_capacity: number(c.reusable_capacity ?? c.open_positions), failed: number(c.failed), candidate_reward: bigint(c.candidate_reward), referral_reward: bigint(c.referral_reward), unit_funding: bigint(c.unit_funding), initial_funding: bigint(c.initial_funding), paid_total: bigint(c.paid_total), refunded_total: bigint(c.refunded_total), locked_total: bigint(c.locked_total), participation_deadline: number(c.participation_deadline), reservation_window: number(c.reservation_window), work_duration: number(c.work_duration), campaign_duration: number(c.campaign_duration ?? (number(c.participation_deadline) - number(c.created_at))), max_pending_per_referrer: number(c.max_pending_per_referrer), state_code: number(c.state_code), created_at: number(c.created_at), closed_at: number(c.closed_at) } as Campaign; }
function position(raw: unknown): Position { const p = normalize(raw); return { ...p, campaign_id: number(p.campaign_id), position_id: number(p.position_id), state_code: number(p.state_code), reserved_at: number(p.reserved_at), reservation_deadline: number(p.reservation_deadline), accepted_at: number(p.accepted_at), work_deadline: number(p.work_deadline), pr_number: number(p.pr_number), attempts: number(p.attempts), active_attempt: number(p.active_attempt), judgment_timeout: number(p.judgment_timeout), retry_deadline: number(p.retry_deadline), outcome_code: number(p.outcome_code), candidate_paid: Boolean(p.candidate_paid), referrer_paid: Boolean(p.referrer_paid), settlement_released: Boolean(p.settlement_released) } as Position; }

export class ReferralRailV2Client {
  readonly referralRailAddress: Address; readonly outcomeJudgeAddress: Address; readonly client: ReturnType<typeof createClient>; readonly account?: Account;
  constructor(config: ReferralRailV2Config) {
    if ((config.chainId ?? V2_CANONICAL.chainId) !== V2_CANONICAL.chainId) throw new ConfigurationError(`ReferralRail v2 is locked to chain ${V2_CANONICAL.chainId}.`);
    if ((config.rpcUrl ?? V2_CANONICAL.rpcUrl) !== V2_CANONICAL.rpcUrl && config.rpcUrl !== "https://studio-next.genlayer.com/api") throw new ConfigurationError(`ReferralRail v2 is locked to ${V2_CANONICAL.rpcUrl}.`);
    this.referralRailAddress = config.referralRailAddress; this.outcomeJudgeAddress = config.outcomeJudgeAddress; this.account = typeof config.account === "string" || !config.account ? undefined : config.account;
    this.client = createClient({ chain: NETWORK, endpoint: V2_CANONICAL.rpcUrl, ...(config.account ? { account: config.account } : {}) });
  }
  static fromPrivateKey(key: `0x${string}`, config: Omit<ReferralRailV2Config, "account">) { return new ReferralRailV2Client({ ...config, account: createAccount(key) }); }
  private get signer(): Account { if (!this.account) throw new ConfigurationError("This operation requires a signing account."); return this.account; }
  private async read(address: Address, functionName: string, args: unknown[] = []) { return this.client.readContract({ address, functionName, args: args as never[], transactionHashVariant: TransactionHashVariant.LATEST_FINAL }); }
  async getCampaign(id: number) { return campaign(await this.read(this.referralRailAddress, "get_campaign", [id])); }
  async listCampaigns(options: { offset?: number; limit?: number } = {}) { const raw = normalize(await this.read(this.referralRailAddress, "list_campaigns", [options.offset ?? 0, options.limit ?? 40])); return (Array.isArray(raw) ? raw : Object.values(raw ?? {})).map(campaign); }
  async getPosition(campaignId: number, positionId: number) { return position(await this.read(this.referralRailAddress, "get_position", [campaignId, positionId])); }
  async listPositions(campaignId: number, options: { offset?: number; limit?: number } = {}) { const raw = normalize(await this.read(this.referralRailAddress, "list_positions", [campaignId, options.offset ?? 0, options.limit ?? 100])); return (Array.isArray(raw) ? raw : Object.values(raw ?? {})).map(position); }
  async getCampaignAccounting(id: number) { const a = normalize(await this.read(this.referralRailAddress, "get_campaign_accounting", [id])); return { ...a, initial_funding: bigint(a.initial_funding), paid: bigint(a.paid), refunded: bigint(a.refunded), still_locked: bigint(a.still_locked), available_capacity: number(a.available_capacity), occupied_capacity: number(a.occupied_capacity), successful: number(a.successful) } as CampaignAccounting; }
  async getProtocolConfig() { return normalize(await this.read(this.referralRailAddress, "get_protocol_config")); }
  async getAvailableActions(campaignId: number, positionId?: number, actor?: Address): Promise<V2Action[]> {
    const c = await this.getCampaign(campaignId); const now = Math.floor(Date.now() / 1000); const employer = actor && actor.toLowerCase() === c.employer.toLowerCase();
    const actions: V2Action[] = [
      { action: "create_referral", allowed: Boolean(actor) && c.state === "ACTIVE" && c.reusable_capacity > 0 && now <= c.participation_deadline && !employer, reason: !actor ? "referrer wallet required" : c.state !== "ACTIVE" ? "campaign is not accepting referrals" : c.reusable_capacity <= 0 ? "no reusable funded capacity" : employer ? "employer cannot refer" : "available", movesFunds: false },
      { action: "join_via_referral", allowed: Boolean(actor) && c.state === "ACTIVE" && c.reusable_capacity > 0 && now <= c.participation_deadline && !employer, reason: !actor ? "candidate wallet required" : employer ? "employer cannot join via referral" : "available", movesFunds: false },
      { action: "close_intake", allowed: Boolean(employer) && c.state === "ACTIVE", reason: employer ? "available" : "employer wallet required", movesFunds: false },
      { action: "cancel_campaign", allowed: Boolean(employer) && c.state === "ACTIVE" && c.occupied === 0, reason: employer ? "available" : "employer wallet required", movesFunds: true },
    ];
    if (positionId === undefined) return actions;
    const p = await this.getPosition(campaignId, positionId); const candidate = actor && actor.toLowerCase() === p.candidate.toLowerCase(); const referrer = actor && actor.toLowerCase() === p.referrer.toLowerCase();
    actions.push({ action: "accept_referral", allowed: candidate && p.state === "RESERVED", reason: candidate ? "available" : "candidate wallet required", movesFunds: false }, { action: "decline_referral", allowed: (candidate || referrer) && p.state === "RESERVED", reason: candidate || referrer ? "available" : "candidate or referrer wallet required", movesFunds: false }, { action: "release_referral", allowed: referrer && p.state === "RESERVED", reason: referrer ? "available" : "referrer wallet required", movesFunds: false });
    if (c.evidence_profile === "GITHUB_PR") actions.push({ action: "submit_work", allowed: candidate && p.state === "ACCEPTED" && now <= p.work_deadline, reason: candidate ? "available before work deadline" : "candidate wallet required", movesFunds: false });
    else actions.push({ action: "submit_evidence", allowed: candidate && p.state === "ACCEPTED" && now <= p.work_deadline, reason: candidate ? "available before work deadline" : "candidate wallet required", movesFunds: false });
    actions.push({ action: "retry_inconclusive", allowed: candidate && p.state === "INCONCLUSIVE" && now <= p.retry_deadline && p.attempts < 2, reason: candidate ? "available during cure window" : "candidate wallet required", movesFunds: false }, { action: "resolve_judgment", allowed: p.state === "JUDGING", reason: p.state === "JUDGING" ? "available after judge finalization" : "position is not judging", movesFunds: false }, { action: "settle_position", allowed: p.state === "COMPLETED", reason: p.state === "COMPLETED" ? "available" : "position is not completed", movesFunds: true }, { action: "recover_position", allowed: ["RESERVED", "ACCEPTED", "JUDGING", "INCONCLUSIVE"].includes(p.state), reason: "contract checks the relevant timeout", movesFunds: true });
    return actions;
  }
  async getJudgment(campaignId: number, positionId: number, attemptId: number) { const raw = normalize(await this.read(this.outcomeJudgeAddress, "get_judgment", [campaignId, positionId, attemptId])); return Object.keys(raw ?? {}).length ? raw : null; }
  async createCampaign(input: CreateCampaignInput): Promise<WriteResult> { const args = [input.title, input.brief, input.criteria, input.evidenceProfile === "GITHUB_PR" ? input.repoOwner ?? "" : "", input.evidenceProfile === "GITHUB_PR" ? input.repoName ?? "" : "", input.evidenceProfile === "GITHUB_PR" ? input.baseBranch ?? "" : "", input.maxPositions, input.candidateReward, input.referralReward, input.reservationWindowSeconds, input.workDurationSeconds, input.campaignDurationSeconds, input.maxPendingPerReferrer, input.evidenceProfile ?? "GITHUB_PR", input.allowedHost ?? "", input.requireWorkChallenge ?? true]; const before = await this.listCampaigns(); return this.write("create_campaign", args, BigInt(input.maxPositions) * (input.candidateReward + input.referralReward), async () => (await this.listCampaigns()).some((c) => !before.some((b) => b.id === c.id) && c.employer.toLowerCase() === this.signer.address.toLowerCase() && c.title === input.title.trim() && c.initial_funding === BigInt(input.maxPositions) * (input.candidateReward + input.referralReward))); }
  async createReferral(campaignId: number, candidate: Address) { const before = await this.listPositions(campaignId); return this.write("create_referral", [campaignId, candidate], 0n, async () => (await this.listPositions(campaignId)).some((p) => !before.some((b) => b.position_id === p.position_id) && p.candidate.toLowerCase() === candidate.toLowerCase() && p.state === "RESERVED")); }
  async joinViaReferral(campaignId: number, referrer: Address) { const before = await this.listPositions(campaignId); return this.write("join_via_referral", [campaignId, referrer], 0n, async () => (await this.listPositions(campaignId)).some((p) => !before.some((b) => b.position_id === p.position_id) && p.candidate.toLowerCase() === this.signer.address.toLowerCase() && p.referrer.toLowerCase() === referrer.toLowerCase() && p.state === "RESERVED")); }
  async acceptReferral(campaignId: number, positionId: number, identityHandle: string) { return this.write("accept_referral", [campaignId, positionId, identityHandle], 0n, async () => (await this.getPosition(campaignId, positionId)).state === "ACCEPTED"); }
  async declineReferral(campaignId: number, positionId: number) { return this.write("decline_referral", [campaignId, positionId], 0n, async () => ["DECLINED", "FAILED"].includes((await this.getPosition(campaignId, positionId)).state)); }
  async releaseReferral(campaignId: number, positionId: number) { return this.write("release_referral", [campaignId, positionId], 0n, async () => ["DECLINED", "FAILED"].includes((await this.getPosition(campaignId, positionId)).state)); }
  async submitWork(campaignId: number, positionId: number, prNumber: number) { return this.write("submit_work", [campaignId, positionId, prNumber], 0n, async () => (await this.getPosition(campaignId, positionId)).state === "JUDGING"); }
  async submitEvidence(campaignId: number, positionId: number, evidenceUri: string) { return this.write("submit_evidence", [campaignId, positionId, evidenceUri], 0n, async () => (await this.getPosition(campaignId, positionId)).state === "JUDGING"); }
  async retryInconclusive(campaignId: number, positionId: number, submission: string | number) { const before = await this.getPosition(campaignId, positionId); return this.write("retry_inconclusive", [campaignId, positionId, String(submission)], 0n, async () => { const next = await this.getPosition(campaignId, positionId); return next.state === "JUDGING" && next.attempts > before.attempts; }); }
  async resolveJudgment(campaignId: number, positionId: number, attemptId: number) { return this.write("resolve_judgment", [campaignId, positionId, attemptId], 0n, async () => ["COMPLETED", "FAILED", "INCONCLUSIVE"].includes((await this.getPosition(campaignId, positionId)).state)); }
  async settlePosition(campaignId: number, positionId: number) { return this.write("settle_position", [campaignId, positionId], 0n, async () => { const p = await this.getPosition(campaignId, positionId); return p.state === "PAID" && p.settlement_released; }); }
  async recoverPosition(campaignId: number, positionId: number) { return this.write("recover_position", [campaignId, positionId], 0n, async () => ["FAILED", "EXPIRED"].includes((await this.getPosition(campaignId, positionId)).state)); }
  async closeIntake(campaignId: number) { return this.write("close_intake", [campaignId], 0n, async () => (await this.getCampaign(campaignId)).state === "RESOLVING"); }
  async finaliseCampaign(campaignId: number) { return this.write("finalise_campaign", [campaignId], 0n, async () => (await this.getCampaign(campaignId)).state === "REFUNDED"); }
  async cancelCampaign(campaignId: number) { return this.write("cancel_campaign", [campaignId], 0n, async () => (await this.getCampaign(campaignId)).state === "CANCELLED"); }
  private async write(method: string, args: unknown[], value: bigint, readback?: () => Promise<boolean>): Promise<WriteResult> { try { const account = this.signer; const fees = await quoteFees(this.client, method, args, account, this.referralRailAddress, value); const hash = await this.client.writeContract({ account, address: this.referralRailAddress, functionName: method, args: args as never[], value, fees }); const txHash = hash as `0x${string}`; await this.client.waitForDecision({ hash: txHash as never, retries: 240, interval: 5000, fullTransaction: true }); try { await this.client.finalizeTransaction({ txId: txHash as never }); } catch {} const tx = await this.client.waitForFinalization({ hash: txHash as never, retries: 240, interval: 5000, fullTransaction: true }); if (!isSuccessful(tx as never)) throw new TransactionError(`${method} finalized unsuccessfully.`, { transaction: tx }); if (readback) { let verified = false; for (let i = 0; i < 8 && !verified; i++) { try { verified = await readback(); } catch {} if (!verified) await new Promise((resolve) => setTimeout(resolve, 1500)); } if (!verified) throw new TransactionError(`${method} finalized but durable v2 readback did not confirm the expected state.`, { txHash }); } return { txHash, successful: true, finalized: true, explorerUrl: explorerTx(txHash), transaction: tx }; } catch (error) { if (error instanceof TransactionError || error instanceof ConfigurationError || error instanceof ValidationError) throw error; throw new TransactionError(`${method} failed: ${redactError(error)}`, error); } }
}